=== camposer/curso_xml_20140602/ejercicio2/ordenadores.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="ordenadores">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ordenador" minOccurs="0" maxOccurs="unbounded" type="ordenadorType"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="ordenadorType">
		<xs:all>
			<xs:element name="nombre" type="xs:string"/>
			<xs:element name="serial" type="serialType"/>
			<xs:element name="persona" type="personaType" minOccurs="0"/>
		</xs:all>
		<xs:attribute name="id" type="xs:integer" use="required"/>
	</xs:complexType>

	<xs:simpleType name="serialType">
		<xs:restriction base="xs:string">
			<xs:pattern value="[0-9]{3,}"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="personaType">
		<xs:sequence>
			<xs:element name="nombre" type="xs:string"/>
			<xs:element name="apellido" type="xs:string"/>
			<xs:element name="fechaNacimiento" type="xs:date"/>
			<xs:element name="altura" type="xs:decimal"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:integer" use="required"/>
	</xs:complexType>

</xs:schema>

=== camposer/curso_xml_20140602/parsers/xsd/ordenadores-all.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="ordenadores.xsl"?>
<ordenadores xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="ordenadores.xsd">
	<ordenador id="1">
		<serial>123</serial>
		<persona id="1">
			<nombre>Juan</nombre>
			<apellido>Pérez</apellido>
			<fechaNacimiento>1980-01-03</fechaNacimiento>
			<altura>180</altura>		
		</persona>
		<nombre>uno</nombre>
	</ordenador>
	<ordenador id="2">
		<nombre>dos</nombre>
		<serial>456</serial>
		<persona id="2">
			<nombre>María</nombre>
			<apellido>González</apellido>
			<fechaNacimiento>1970-04-20</fechaNacimiento>
			<altura>160</altura>
		</persona>
	</ordenador>
	<ordenador id="3">
		<nombre>tres</nombre>
		<serial>789</serial>
		<persona id="3">
			<nombre>Pedro</nombre>
			<apellido>García</apellido>
			<fechaNacimiento>1971-05-18</fechaNacimiento>
			<altura>170</altura>
		</persona>
	</ordenador>
	<ordenador id="4">
		<nombre>cuatro</nombre>
		<serial>012</serial>
		<persona id="1">
			<nombre>Juan</nombre>
			<apellido>Pérez</apellido>
			<fechaNacimiento>1980-01-03</fechaNacimiento>
			<altura>180</altura>		
		</persona>
	</ordenador>
</ordenadores>
