=== camposer/curso_xml_20140602/basico/ciudades.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="ciudades">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ciudad" type="ciudadTipo" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="ciudadTipo">
		<xs:sequence>
			<xs:element name="nombre" type="xs:string"/>
			<xs:element name="pais" type="xs:string"/>
			<xs:element name="continente" type="continenteTipo"/>
			<xs:element name="poblacion" type="xs:decimal"/>
			<xs:element name="transportes" type="transporteTipo" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:integer" use="required"/>
	</xs:complexType>

	<xs:complexType name="transporteTipo">
		<xs:sequence>
			<xs:element name="transporte" maxOccurs="unbounded">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:string"><!-- Definición del contenido -->
							<xs:attribute name="tipo" type="transporteTipoTipo" /><!-- Definición del atributo -->
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:simpleType name="continenteTipo">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Africa"/>
			<xs:enumeration value="América"/>
			<xs:enumeration value="Asia"/>
			<xs:enumeration value="Europa"/>
			<xs:enumeration value="Oceanía"/>
		</xs:restriction>
	</xs:simpleType> 

	<xs:simpleType name="transporteTipoTipo">
		<xs:restriction base="xs:string">
			<xs:pattern value="(Bus|Acu[áa]tico|Tranv[íi]a|Metro)"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== camposer/curso_xml_20140602/basico/ciudades-xsd.xml
<?xml version="1.0" encoding="utf-8" ?>
<ciudades xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="ciudades.xsd">
	<ciudad id="1">
		<nombre>Madrid</nombre>
		<pais>España</pais>
		<continente>Europa</continente>
		<poblacion>4000</poblacion>
		<transportes>
			<transporte tipo="Metro">Metro de Madrid</transporte>
			<transporte tipo="Bus">Buses de Madrid</transporte>
		</transportes>
	</ciudad>
	<ciudad id="2">
		<nombre>Venecia</nombre>
		<pais>Italia</pais>
		<continente>Europa</continente>
		<poblacion>1000</poblacion>
		<transportes>
			<transporte tipo="Acuático">Vaporetto</transporte>
			<transporte tipo="Bus">Buses de Venecia</transporte>
		</transportes>
	</ciudad>
	<ciudad id="3">
		<nombre>Buenos Aires</nombre>
		<pais>Argentina</pais>
		<continente>América</continente>
		<poblacion>10000</poblacion>
		<transportes>
			<transporte tipo="Metro">Subte</transporte>
			<transporte tipo="Bus">Buses de Baires</transporte>
		</transportes>
	</ciudad>
</ciudades>
