=== camposer/curso_xml_20140602/basico/coches.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="coches">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="coche" type="cocheType" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="cocheType">
		<xs:sequence>
			<xs:element name="marca" type="cocheMarcaType"/>
			<xs:element name="modelo" type="xs:string"/>
			<xs:element name="matricula" type="cocheMatriculaType"/>
			<xs:element name="anio" type="xs:integer"/>
			<xs:element name="duenio" type="duenioType"/>
			<xs:element name="accesorios" type="accesoriosType"/>
		</xs:sequence>		
		<xs:attribute name="id" type="xs:int" use="required"/>
	</xs:complexType>

	<xs:complexType name="duenioType">
		<xs:sequence>
			<xs:element name="dni" type="xs:string"/>
			<xs:element name="nombre" type="xs:string"/>
			<xs:element name="apellido" type="xs:string"/>
		</xs:sequence>		
	</xs:complexType>

	<xs:complexType name="accesoriosType">
		<xs:sequence>
			<xs:element name="accesorio" minOccurs="1" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="nombre" type="xs:string"/>
						<xs:element name="tipo" type="xs:string" minOccurs="0"/>
						<xs:element name="modelo" type="xs:string" minOccurs="0"/>
					</xs:sequence>		
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:simpleType name="cocheMarcaType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Ford"/>
			<xs:enumeration value="Seat"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="cocheMatriculaType">
		<xs:restriction base="xs:string">
			<xs:pattern value="[0-9]{3,}"/>
		</xs:restriction>
	</xs:simpleType>

</xs:schema>

=== camposer/curso_xml_20140602/basico/coches-xsd.xml
<?xml version="1.0" encoding="utf-8" ?>
<coches xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="coches.xsd">
	<coche id="1">
		<marca>Ford</marca>
		<modelo>Fiesta</modelo>
		<matricula>1234</matricula>	
		<anio>2010</anio>	
		<duenio>
			<dni>123</dni>
			<nombre>Juan</nombre>
			<apellido>Pérez</apellido>
		</duenio>
		<accesorios>
			<accesorio>
				<nombre>Radio</nombre>
				<tipo>USB</tipo>
			</accesorio>
			<accesorio>
				<nombre>Climatizador</nombre>
				<modelo>3457T</modelo>
			</accesorio>
		</accesorios>
	</coche>
	<coche id="2">
		<marca>Ford</marca>
		<modelo>Focus</modelo>
		<matricula>5678</matricula>	
		<anio>2009</anio>	
		<duenio>
			<dni>456</dni>
			<nombre>María</nombre>
			<apellido>García</apellido>
		</duenio>
		<accesorios>
			<accesorio>
				<nombre>Radio</nombre>
				<tipo>CD</tipo>
			</accesorio>
		</accesorios>
	</coche>
	<coche id="3">
		<marca>Seat</marca>
		<modelo>Leon</modelo>
		<matricula>98765</matricula>	
		<anio>2002</anio>	
		<duenio>
			<dni>456</dni>
			<nombre>María</nombre>
			<apellido>García</apellido>
		</duenio>
		<accesorios>
			<accesorio>
				<nombre>Radio</nombre>
				<tipo>DVD</tipo>
			</accesorio>
			<accesorio>
				<nombre>Bluetooth</nombre>
			</accesorio>
		</accesorios>
	</coche>
</coches>
